title: QuickShelf
description: A lightning-fast macOS menu-bar “shelf” that shows any folder’s contents for instant drag & drop access
baseurl: ""
url: "https://quickshelf-app.slowlab.dev"

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  sass_dir: assets/css
  style: compressed

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"